version: '3.8'

# File Distribution Mode Test - 1 Master + 2 Workers
# Workers do NOT have access to media files
# All file transfers happen via HTTP

services:
  # Master Server - Has access to media library
  master:
    build: .
    container_name: av1-master
    restart: unless-stopped
    command: python3 master_server.py
    ports:
      - "8090:8090"
    volumes:
      # Master has access to media files
      - ./TestLib:/media/TestLib:ro
      
      # Persistent data (database + config)
      - ./master-data:/data
      
      # Temp directory for file processing
      - ./master-temp:/tmp/av1_transcoding
    environment:
      # Python
      - PYTHONUNBUFFERED=1
      
      # Application Configuration
      - MEDIA_DIRS=/media/TestLib
      - TEMP_DIR=/tmp/av1_transcoding
      - WEB_PORT=8090
      - TESTING_MODE=true
      - DB_PATH=/data/transcoding.db
      - CONFIG_DIR=/data/config
      
      # Encoding Settings (fast for testing)
      - SVT_AV1_PRESET=8
      
    networks:
      - av1-network

  # Worker 1 - No media access, receives files via HTTP
  worker1:
    build: .
    container_name: av1-worker1
    restart: unless-stopped
    command: python3 worker_client.py http://master:8090
    volumes:
      # NO media directory! Files come from master via HTTP
      
      # Worker config directory
      - ./worker1-data:/data
      
      # Temp directory for processing
      - ./worker1-temp:/tmp/av1_transcoding
    environment:
      # Python
      - PYTHONUNBUFFERED=1
      
      # Master Connection
      - MASTER_URL=http://master:8090
      
      # Application Configuration
      - TEMP_DIR=/tmp/av1_transcoding
      - CONFIG_DIR=/data/config
      
      # FILE DISTRIBUTION MODE - ENABLED
      - FILE_DISTRIBUTION_MODE=true
      
      # Encoding Settings
      - SVT_AV1_PRESET=8
      
    depends_on:
      - master
    networks:
      - av1-network

  # Worker 2 - No media access, receives files via HTTP
  worker2:
    build: .
    container_name: av1-worker2
    restart: unless-stopped
    command: python3 worker_client.py http://master:8090
    volumes:
      # NO media directory! Files come from master via HTTP
      
      # Worker config directory
      - ./worker2-data:/data
      
      # Temp directory for processing
      - ./worker2-temp:/tmp/av1_transcoding
    environment:
      # Python
      - PYTHONUNBUFFERED=1
      
      # Master Connection
      - MASTER_URL=http://master:8090
      
      # Application Configuration
      - TEMP_DIR=/tmp/av1_transcoding
      - CONFIG_DIR=/data/config
      
      # FILE DISTRIBUTION MODE - ENABLED
      - FILE_DISTRIBUTION_MODE=true
      
      # Encoding Settings
      - SVT_AV1_PRESET=8
      
    depends_on:
      - master
    networks:
      - av1-network

networks:
  av1-network:
    driver: bridge
