version: '3.8'

# Production deployment using GitHub Container Registry images
# Pull images: docker pull ghcr.io/hack2c/av1-distributed-encoder:latest

services:
  # Master Server
  master:
    image: ghcr.io/hack2c/av1-distributed-encoder:latest
    container_name: av1-master
    restart: unless-stopped
    command: python3 master_server.py
    ports:
      - "8090:8090"
    volumes:
      # Mount your media library (read-only)
      - /path/to/your/media:/media:ro
      
      # Persistent data (database + config)
      - ./master-data:/data
      
      # Temp directory
      - ./master-temp:/tmp/av1_transcoding
    environment:
      # User/Group for file permissions
      - PUID=1000
      - PGID=1000
      
      # Application Configuration
      - MEDIA_DIRS=/media
      - TEMP_DIR=/tmp/av1_transcoding
      - WEB_PORT=8090
      - DB_PATH=/data/transcoding.db
      - CONFIG_DIR=/data/config
      
      # Encoding Settings
      - SVT_AV1_PRESET=4
      
      # Optional: SMB/CIFS mount
      # - SMB_HOST=nas.local
      # - SMB_SHARE=Media
      # - SMB_USERNAME=user
      # - SMB_PASSWORD=pass
      
    networks:
      - av1-network

  # Worker 1
  worker1:
    image: ghcr.io/hack2c/av1-distributed-encoder:latest
    container_name: av1-worker1
    restart: unless-stopped
    command: python3 worker_client.py http://master:8090
    volumes:
      # Worker config
      - ./worker1-data:/data
      
      # Temp directory
      - ./worker1-temp:/tmp/av1_transcoding
    environment:
      # User/Group for file permissions
      - PUID=1000
      - PGID=1000
      
      # Master Connection
      - MASTER_URL=http://master:8090
      
      # Application Configuration
      - TEMP_DIR=/tmp/av1_transcoding
      - CONFIG_DIR=/data/config
      
      # FILE DISTRIBUTION MODE
      - FILE_DISTRIBUTION_MODE=true
      
      # Encoding Settings
      - SVT_AV1_PRESET=4
      
    depends_on:
      - master
    networks:
      - av1-network

  # Worker 2
  worker2:
    image: ghcr.io/hack2c/av1-distributed-encoder:latest
    container_name: av1-worker2
    restart: unless-stopped
    command: python3 worker_client.py http://master:8090
    volumes:
      # Worker config
      - ./worker2-data:/data
      
      # Temp directory
      - ./worker2-temp:/tmp/av1_transcoding
    environment:
      # User/Group for file permissions
      - PUID=1000
      - PGID=1000
      
      # Master Connection
      - MASTER_URL=http://master:8090
      
      # Application Configuration
      - TEMP_DIR=/tmp/av1_transcoding
      - CONFIG_DIR=/data/config
      
      # FILE DISTRIBUTION MODE
      - FILE_DISTRIBUTION_MODE=true
      
      # Encoding Settings
      - SVT_AV1_PRESET=4
      
    depends_on:
      - master
    networks:
      - av1-network

networks:
  av1-network:
    driver: bridge
