version: '3.8'

# Test deployment using GitHub Container Registry images
# Testing with TestLib/TV and TV directories

services:
  # Master Server
  master:
    image: ghcr.io/hack2c/av1-distributed-encoder:latest
    container_name: av1-master
    restart: unless-stopped
    command: python3 master_server.py
    ports:
      - "8090:8090"
    volumes:
      # Test libraries
      - ./TestLib/TV:/media/TestLib/TV:ro
      - ./TV:/media/TV:ro
      
      # Persistent data (database + config)
      - ./master-data:/data
      
      # Temp directory
      - ./master-temp:/tmp/av1_transcoding
    environment:
      # Python
      - PYTHONUNBUFFERED=1
      
      # User/Group for file permissions
      - PUID=1000
      - PGID=1000
      
      # Application Configuration
      - MEDIA_DIRS=/media/TestLib/TV,/media/TV
      - TEMP_DIR=/tmp/av1_transcoding
      - WEB_PORT=8090
      - TESTING_MODE=true
      - DB_PATH=/data/transcoding.db
      - CONFIG_DIR=/data/config
      
      # Encoding Settings - PRESET 0 (Slowest/Highest Quality)
      - SVT_AV1_PRESET=0
      
    networks:
      - av1-network

  # Worker 1 - File distribution mode
  worker1:
    image: ghcr.io/hack2c/av1-distributed-encoder:latest
    container_name: av1-worker1
    restart: unless-stopped
    command: python3 worker_client.py http://master:8090
    volumes:
      # NO media directory! Files come from master via HTTP
      
      # Worker config
      - ./worker1-data:/data
      
      # Temp directory
      - ./worker1-temp:/tmp/av1_transcoding
    environment:
      # Python
      - PYTHONUNBUFFERED=1
      
      # User/Group for file permissions
      - PUID=1000
      - PGID=1000
      
      # Master Connection
      - MASTER_URL=http://master:8090
      
      # Application Configuration
      - TEMP_DIR=/tmp/av1_transcoding
      - CONFIG_DIR=/data/config
      
      # FILE DISTRIBUTION MODE - ENABLED
      - FILE_DISTRIBUTION_MODE=true
      
      # Encoding Settings - PRESET 0 (Slowest/Highest Quality)
      - SVT_AV1_PRESET=0
      
    depends_on:
      - master
    networks:
      - av1-network

  # Worker 2 - File distribution mode
  worker2:
    image: ghcr.io/hack2c/av1-distributed-encoder:latest
    container_name: av1-worker2
    restart: unless-stopped
    command: python3 worker_client.py http://master:8090
    volumes:
      # NO media directory! Files come from master via HTTP
      
      # Worker config
      - ./worker2-data:/data
      
      # Temp directory
      - ./worker2-temp:/tmp/av1_transcoding
    environment:
      # Python
      - PYTHONUNBUFFERED=1
      
      # User/Group for file permissions
      - PUID=1000
      - PGID=1000
      
      # Master Connection
      - MASTER_URL=http://master:8090
      
      # Application Configuration
      - TEMP_DIR=/tmp/av1_transcoding
      - CONFIG_DIR=/data/config
      
      # FILE DISTRIBUTION MODE - ENABLED
      - FILE_DISTRIBUTION_MODE=true
      
      # Encoding Settings - PRESET 0 (Slowest/Highest Quality)
      - SVT_AV1_PRESET=0
      
    depends_on:
      - master
    networks:
      - av1-network

networks:
  av1-network:
    driver: bridge
